// import { inspect } from 'util';
import { Response } from 'express';
import logger from '../../../services/firebase/logger';
import prismaInstance from '../../../services/prisma';
import { CustomRequest, FirebaseJwtToken } from '../../../types';
import { StripeFirestoreService } from '../../stripe/db';
import { firebaseAdmin } from '../../../services/firebase/admin';

const handler = async (req: any | CustomRequest, res: Response) => {
  try {
    const firebaseUser: FirebaseJwtToken = req.firebase_user_info;

    logger.info(`/auth/register started:
      | req.body: ${JSON.stringify(req.body)}
      | req.params: ${JSON.stringify(req.params)}
      | firebaseUser: ${JSON.stringify(firebaseUser)}`);

    if (!firebaseUser) {
      res.status(401).json({
        success: false,
        error: 'Unauthorized: Missing Firebase JWT token',
      });
      return;
    }

    // Extract Firebase user ID - this is NOT the api_user_id, it's the Firebase UID
    const firebaseUserId =
      firebaseUser.user_id || firebaseUser.uid || firebaseUser.sub;

    if (!firebaseUserId) {
      res.status(401).json({
        success: false,
        error: 'Unauthorized: Firebase user ID could not be determined',
      });
      return;
    }

    // Add input validation
    if (!firebaseUser.email) {
      res.status(400).json({
        success: false,
        error: 'Email is required for registration',
      });
      return;
    }

    // Extract autoVerify flag from request body (optional)
    const autoVerify = req.body?.autoVerify || false;

    // Create or update user in our database using Firebase UID
    const user = await prismaInstance.user.upsert({
      where: {
        firebase_user_id: firebaseUserId, // This is the Firebase UID, not our api_user_id
      },
      update: {
        updated_at: new Date(),
      },
      create: {
        firebase_user_id: firebaseUserId, // Store Firebase UID for reference
        // user_id (which becomes api_user_id) is auto-generated by @default(uuid())
        // createdAt is auto-generated by @default(now())
        // updatedAt is auto-generated by @default(now()) on creation
      },
      select: {
        user_id: true, // This is our internal api_user_id (UUID)
        firebase_user_id: true, // This is the Firebase UID for reference
      },
    });

    logger.info(`User successfully registered
      | api_user_id=${user.user_id}
      | firebase_user_id=${firebaseUserId}
      | auto_verify=${autoVerify}
      | gcp_project_id=${process.env.GCP_PROJECT_ID}
    `);

    // UAT BYPASS: Auto-verify email for UAT environment if autoVerify flag is true
    if (autoVerify) {
      try {
        logger.info(
          `UAT auto-verify: Verifying email for user ${firebaseUserId}`,
        );
        await firebaseAdmin.auth().updateUser(firebaseUserId, {
          emailVerified: true,
        });
        logger.info(
          `UAT auto-verify: Email verified successfully for user ${firebaseUserId}`,
        );
      } catch (autoVerifyError) {
        // Non-blocking: Log warning but don't fail the registration
        logger.warn(
          `UAT auto-verify: Failed to auto-verify email for user ${firebaseUserId}`,
          {
            error:
              autoVerifyError instanceof Error
                ? autoVerifyError.message
                : String(autoVerifyError),
          },
        );
      }
    }

    // Create or update Firestore account record
    try {
      const firestoreAccount =
        await StripeFirestoreService.getAccountByFirebaseUid(firebaseUserId);

      if (!firestoreAccount) {
        // Create default Firestore account record
        const defaultAccountData = {
          api_user_id: user.user_id,
          firebase_user_id: firebaseUserId,
          email: firebaseUser.email || '', // Get email from Firebase token
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString(),
        };

        await StripeFirestoreService.createAccount(defaultAccountData);

        logger.info('FIRESTORE_ACCOUNT_CREATED_ON_REGISTER', {
          api_user_id: user.user_id,
          firebase_user_id: firebaseUserId,
          email: firebaseUser.email,
        });
      } else {
        // Update the existing account's updated_at timestamp and ensure api_user_id is correct
        await StripeFirestoreService.updateAccount(user.user_id, {
          api_user_id: user.user_id, // Ensure api_user_id is up to date
          updated_at: new Date().toISOString(),
        });

        logger.info('FIRESTORE_ACCOUNT_UPDATED_ON_REGISTER', {
          api_user_id: user.user_id,
          firebase_user_id: firebaseUserId,
        });
      }
    } catch (firestoreError) {
      // Log the error but don't fail the registration process
      logger.warn('FIRESTORE_ACCOUNT_CHECK_ERROR_ON_REGISTER', {
        error: firestoreError,
        api_user_id: user.user_id,
        firebase_user_id: firebaseUserId,
        error_details:
          firestoreError instanceof Error
            ? firestoreError.message
            : 'Unknown error',
      });
    }

    res.status(200).json({
      success: true,
      api_user_id: user.user_id, // Our internal UUID for API operations
      firebase_user_id: firebaseUserId, // Firebase UID for reference
      // Deprecated: keeping for backward compatibility only
      user_id: user.user_id, // @deprecated Use api_user_id instead
    });
  } catch (error) {
    logger.error('Error in register endpoint:', error as any);

    let statusCode = 500;
    let errorMessage = 'An unexpected error occurred during registration.';

    if (error instanceof Error) {
      errorMessage = error.message;

      // Handle specific database errors
      if (error.message.includes('Unique constraint')) {
        statusCode = 409;
        errorMessage = 'User already exists';
      } else if (error.message.toLowerCase().includes('unauthorized')) {
        statusCode = 401;
      } else if (error.message.includes('timeout')) {
        statusCode = 408;
        errorMessage = 'Database operation timed out. Please try again.';
      }
    }

    res.status(statusCode).json({
      success: false,
      error: errorMessage,
    });
  }
};

export default handler;
