// import { inspect } from 'util';
import { Response } from 'express';
import logger from '../../../services/firebase/logger';
import prismaInstance from '../../../services/prisma';
import { CustomRequest, FirebaseJwtToken } from '../../../types';

const handler = async (req: any | CustomRequest, res: Response) => {
  try {
    const firebaseUser: FirebaseJwtToken = req.firebase_user_info;

    logger.info(`req.firebase_user_info: ${JSON.stringify(firebaseUser)}`);

    if (!firebaseUser) {
      res.status(401).json({
        success: false,
        error: 'Unauthorized: Missing Firebase JWT token',
      });
    }

    const firebaseUserId = firebaseUser.user_id as string;

    if (!firebaseUserId) {
      res.status(401).json({
        success: false,
        error: 'Unauthorized: Firebase user ID could not be determined',
      });
    }

    const user = await prismaInstance.user.upsert({
      where: {
        firebase_user_id: firebaseUserId,
      },
      update: {
        updated_at: new Date(),
      },
      create: {
        firebase_user_id: firebaseUserId,
        // user_id is auto-generated by @default(uuid())
        // createdAt is auto-generated by @default(now())
        // updatedAt is auto-generated by @default(now()) on creation
      },
      select: {
        user_id: true,
      },
    });

    res.status(200).json({
      success: true,
      user_id: user.user_id,
    });
  } catch (error) {
    logger.error('Error in register endpoint:', error as any);

    let statusCode = 500;
    let errorMessage = 'An unexpected error occurred during registration.';

    if (error instanceof Error) {
      errorMessage = error.message;

      if (error.message.toLowerCase().includes('unauthorized')) {
        statusCode = 401;
      }
    }

    res.status(statusCode).json({
      success: false,
      error: errorMessage,
    });
  }
};

export default handler;
