/**
 * Genkit domain types shared across AI generation flows.
 *
 * Centralizes input/output contracts used by services in `src/services/genkit/*`.
 */

/** Configuration options for Genkit text generation. */
export interface GenerationConfig {
  maxOutputTokens?: number;
  temperature?: number;
  topP?: number;
  topK?: number;
}

/** Exam planner topic item written to RTDB `exam_plans/{exam_id}`. */
export interface ExamPlanQuestion {
  exam_topic: string;
  question_id: string | null;
}

/** Exam plan payload generated by `examPlanner`. */
export interface ExamPlan {
  questions: ExamPlanQuestion[];
  cert_id: string;
  user_id: string;
  created_at: number;
  customPrompt?: string | null;
  lastExamReport?: string | null;
}

/** Input payload for `examPlanner` flow. */
export interface ExamPlannerInputData {
  cert_name: string;
  totalQuestionCounts: number;
  exam_id: string;
  cert_id: string;
  user_id: string;
  customPrompt?: string | null;
  lastExamReport?: string | null;
}

/** Single quiz item generated by `quizGenerator`. */
export interface QuizItem {
  question: string;
  choices: string[];
  answerIndex: number;
  explanation: string;
  examTopic: string;
  exam_id: string;
}

/** Input payload for `quizGenerator` flow. */
export interface QuizGeneratorInputData {
  subject: string;
  examTopicList: string[];
  exam_id: string;
  customPromptText?: string;
  lastExamReport?: string;
}

/** Topic-level performance input used by exam report generation. */
export interface ExamReportTopicPerformanceInput {
  topic: string;
  correct_answers: number;
  total_attempts: number;
  accuracy_rate: number;
  current_difficulty_level: number;
  average_difficulty_attempted: number;
}

/** Input contract for `examReportGenerator` flow. */
export interface ExamReportGeneratorInput {
  user_id: string;
  exam_id: string;
  certification_name: string;
  performance_data: ExamReportTopicPerformanceInput[];
  overall_score: number;
  total_questions: number;
  correct_answers: number;
}

/** Difficulty adjustment output generated by exam report flow. */
export interface ExamReportDifficultyAdjustments {
  increase_difficulty: string[];
  maintain_difficulty: string[];
  decrease_difficulty: string[];
}

/** Output contract for `examReportGenerator` flow. */
export interface ExamReportGeneratorOutput {
  report: string;
  difficulty_adjustments: ExamReportDifficultyAdjustments;
}

/** Callable flow type for exam report generation. */
export type ExamReportGeneratorFlow = (
  input: ExamReportGeneratorInput,
) => Promise<ExamReportGeneratorOutput>;

/** Mastery level labels used by certification summary generation. */
export type TopicMasteryLevel =
  | 'novice'
  | 'developing'
  | 'proficient'
  | 'advanced'
  | 'expert';

/** Topic mastery aggregate used by certification summary input. */
export interface CertSummaryTopicMastery {
  topic: string;
  exams_covered: number;
  average_accuracy: number;
  mastery_level: TopicMasteryLevel;
  total_questions: number;
  total_correct: number;
}

/** Input contract for `certSummaryGenerator` flow. */
export interface CertSummaryGeneratorInput {
  user_id: string;
  cert_id: string;
  certification_name: string;
  total_exams_taken: number;
  average_score: number;
  best_score: number;
  worst_score: number;
  performance_trend: 'improving' | 'declining' | 'stable';
  topic_mastery: CertSummaryTopicMastery[];
  strong_topics: string[];
  weak_topics: string[];
  overall_accuracy_rate: number;
}

/** Insight section generated by certification summary flow. */
export interface CertSummaryLearningInsights {
  mastery_progression: string;
  consistency_analysis: string;
  readiness_assessment: string;
}

/** Output contract for `certSummaryGenerator` flow. */
export interface CertSummaryGeneratorOutput {
  summary: string;
  learning_insights: CertSummaryLearningInsights;
}

/** Callable flow type for certification summary generation. */
export type CertSummaryGeneratorFlow = (
  input: CertSummaryGeneratorInput,
) => Promise<CertSummaryGeneratorOutput>;

/** Per-question incorrect answer context used by knowledge pooling flow. */
export interface KnowledgeIncorrectAnswerData {
  exam_id: string;
  question_id: string;
  topic: string | null;
  question_text: string;
  correct_answer: string;
  user_selected_answer: string;
  explanation: string | null;
}

/** Generated knowledge insight item. */
export interface KnowledgeInsight {
  insight: string;
  topic: string;
}

/** Input contract for `knowledgePoolingGenerator` flow. */
export interface KnowledgePoolingGeneratorInput {
  user_id: string;
  exam_id: string;
  cert_id: number;
  certification_name: string;
  exam_guide_url: string | null;
  incorrect_answers_data: KnowledgeIncorrectAnswerData[];
}

/** Output contract for `knowledgePoolingGenerator` flow. */
export interface KnowledgePoolingGeneratorOutput {
  knowledge_insights: KnowledgeInsight[];
  summary: string;
}

/** Callable flow type for knowledge pooling generation. */
export type KnowledgePoolingGeneratorFlow = (
  input: KnowledgePoolingGeneratorInput,
) => Promise<KnowledgePoolingGeneratorOutput>;

/** Metrics describing adaptive quiz topic composition. */
export interface AdaptiveQuizMetrics {
  totalCount: number;
  uniqueTopicsCount: number;
  duplicateTopicsCount: number;
  duplicateTopics: string[];
}
