import logger from '../../../services/firebase/logger';

export interface TaskPayload {
  exam_id: string;
  cert_id: number;
  certification_name: string;
  batch_number: number;
  total_batches: number;
  custom_prompt_text?: string;
  questions_per_batch: number;
  last_exam_report?: string;
}

export interface ExamTopicItem {
  exam_topic: string;
  question_id: string | null;
}

/**
 * Logs a summary of question-topic associations for debugging and monitoring
 * @param exam_id - The exam identifier
 * @param examTopicList - Current topic list with question associations
 * @param context - Context for the logging (e.g., 'after_batch_creation')
 */
export function logQuestionTopicAssociationSummary(
  exam_id: string,
  examTopicList: ExamTopicItem[],
  context: string,
): void {
  const assignedTopics = examTopicList.filter((t) => t.question_id !== null);
  const unassignedTopics = examTopicList.filter((t) => t.question_id === null);

  logger.info(`QUESTION_TOPIC_SUMMARY: ${context} for exam_id=${exam_id}`, {
    exam_id,
    context,
    summary: {
      total_topics: examTopicList.length,
      assigned_topics: assignedTopics.length,
      unassigned_topics: unassignedTopics.length,
      completion_percentage: Math.round(
        (assignedTopics.length / examTopicList.length) * 100,
      ),
    },
    assigned_mappings: assignedTopics.map((t) => ({
      exam_topic: t.exam_topic,
      question_id: t.question_id,
    })),
    unassigned_topics: unassignedTopics.map((t) => t.exam_topic),
    structuredData: true,
  });
}

/**
 * Normalizes exam topic text for consistent matching
 * @param topicText - The topic text to normalize
 * @returns Normalized topic text
 */
export function normalizeExamTopic(topicText: string): string {
  return topicText.trim().toLowerCase().replace(/\s+/g, ' ');
}

/**
 * Finds the best matching exam topic from the list
 * @param generatedTopic - The topic generated by AI
 * @param examTopicList - The list of exam topics from RTDB
 * @returns The matching exam topic item or null if not found
 */
export function findMatchingExamTopic(
  generatedTopic: string,
  examTopicList: ExamTopicItem[],
): ExamTopicItem | null {
  const normalizedGenerated = normalizeExamTopic(generatedTopic);

  // First try exact match (normalized)
  const exactMatch = examTopicList.find(
    (topic) =>
      topic.question_id === null &&
      normalizeExamTopic(topic.exam_topic) === normalizedGenerated,
  );

  if (exactMatch) {
    return exactMatch;
  }

  // Try partial match (contains)
  const partialMatch = examTopicList.find(
    (topic) =>
      topic.question_id === null &&
      (normalizeExamTopic(topic.exam_topic).includes(normalizedGenerated) ||
        normalizedGenerated.includes(normalizeExamTopic(topic.exam_topic))),
  );

  if (partialMatch) {
    logger.info(
      `TOPIC_PARTIAL_MATCH: Generated="${generatedTopic}" matched with "${partialMatch.exam_topic}"`,
      {
        generated_topic: generatedTopic,
        matched_topic: partialMatch.exam_topic,
        structuredData: true,
      },
    );
    return partialMatch;
  }

  logger.warn(
    `TOPIC_NO_MATCH: Generated topic "${generatedTopic}" could not be matched`,
    {
      generated_topic: generatedTopic,
      available_topics: examTopicList
        .filter((t) => t.question_id === null)
        .map((t) => t.exam_topic),
      structuredData: true,
    },
  );

  return null;
}

/**
 * Updates the examTopicList with generated question IDs - only for successfully validated questions
 * @param examTopicList - The original topic list
 * @param createdQuestions - The questions created in the database
 * @param validQuestionResults - The validation results for questions that passed validation
 * @returns Updated topic list with question IDs assigned only for valid questions
 */
export function updateTopicListWithQuestionIds(
  examTopicList: ExamTopicItem[],
  createdQuestions: any[],
  validQuestionResults: Array<{
    question: any;
    matchingTopic: ExamTopicItem | null;
  }>,
): ExamTopicItem[] {
  const updatedTopicList = [...examTopicList];
  const associationsMade: Array<{
    exam_topic: string;
    question_id: string;
    topicIndex: number;
    matching_strategy: 'exact' | 'partial' | 'fallback';
  }> = [];

  createdQuestions.forEach((createdQuestion, index) => {
    const validationResult = validQuestionResults[index];
    const questionId = createdQuestion.quiz_question_id;
    const generatedTopic = validationResult.question.examTopic.trim();

    // Use the pre-validated matching topic from validation results
    const matchingTopic = validationResult.matchingTopic;
    let matchingStrategy: 'exact' | 'partial' | 'fallback' = 'exact';

    // If we have a pre-validated matching topic, use it
    if (matchingTopic) {
      // Check if the pre-validated topic is still available
      const topicIndex = updatedTopicList.findIndex(
        (topic) =>
          topic.exam_topic === matchingTopic!.exam_topic &&
          topic.question_id === null,
      );

      if (topicIndex !== -1) {
        // Assign to the pre-validated matching topic
        updatedTopicList[topicIndex] = {
          ...updatedTopicList[topicIndex],
          question_id: questionId,
        };

        // Determine matching strategy based on topic similarity
        const normalizedGenerated = normalizeExamTopic(generatedTopic);
        const normalizedMatched = normalizeExamTopic(matchingTopic.exam_topic);

        if (normalizedGenerated === normalizedMatched) {
          matchingStrategy = 'exact';
        } else if (
          normalizedGenerated.includes(normalizedMatched) ||
          normalizedMatched.includes(normalizedGenerated)
        ) {
          matchingStrategy = 'partial';
        } else {
          matchingStrategy = 'fallback';
        }

        associationsMade.push({
          exam_topic: matchingTopic.exam_topic,
          question_id: questionId,
          topicIndex,
          matching_strategy: matchingStrategy,
        });

        logger.info(
          `TOPIC_QUESTION_ASSOCIATED: exam_topic="${matchingTopic.exam_topic}", generated_topic="${generatedTopic}", question_id=${questionId}, strategy=${matchingStrategy}`,
          {
            exam_topic: matchingTopic.exam_topic,
            generated_topic: generatedTopic,
            question_id: questionId,
            topic_index: topicIndex,
            matching_strategy: matchingStrategy,
            structuredData: true,
          },
        );
      } else {
        // Pre-validated topic is no longer available, try fallback
        const firstAvailableIndex = updatedTopicList.findIndex(
          (topic) => topic.question_id === null,
        );

        if (firstAvailableIndex !== -1) {
          updatedTopicList[firstAvailableIndex] = {
            ...updatedTopicList[firstAvailableIndex],
            question_id: questionId,
          };

          associationsMade.push({
            exam_topic: updatedTopicList[firstAvailableIndex].exam_topic,
            question_id: questionId,
            topicIndex: firstAvailableIndex,
            matching_strategy: 'fallback',
          });

          logger.warn(
            `TOPIC_FALLBACK_ASSOCIATION: Pre-validated topic "${matchingTopic.exam_topic}" no longer available, assigned to "${updatedTopicList[firstAvailableIndex].exam_topic}"`,
            {
              generated_topic: generatedTopic,
              pre_validated_topic: matchingTopic.exam_topic,
              assigned_topic: updatedTopicList[firstAvailableIndex].exam_topic,
              question_id: questionId,
              topic_index: firstAvailableIndex,
              structuredData: true,
            },
          );
        } else {
          logger.error(
            `TOPIC_ASSOCIATION_FAILED: No available topic slots remaining for validated question`,
            {
              generated_topic: generatedTopic,
              question_id: questionId,
              pre_validated_topic: matchingTopic.exam_topic,
              remaining_topics: updatedTopicList.filter(
                (t) => t.question_id === null,
              ).length,
              structuredData: true,
            },
          );
        }
      }
    } else {
      // This shouldn't happen for validated questions, but handle as error
      logger.error(
        `VALIDATION_ERROR: Valid question without matching topic - this indicates a validation bug`,
        {
          generated_topic: generatedTopic,
          question_id: questionId,
          available_topics: updatedTopicList
            .filter((t) => t.question_id === null)
            .map((t) => t.exam_topic),
          structuredData: true,
        },
      );
    }
  });

  // Enhanced logging with matching strategy breakdown
  const strategyBreakdown = associationsMade.reduce((acc, assoc) => {
    acc[assoc.matching_strategy] = (acc[assoc.matching_strategy] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  logger.info(
    `TOPIC_ASSOCIATIONS_BATCH: ${associationsMade.length} topic-question associations completed`,
    {
      associations_count: associationsMade.length,
      strategy_breakdown: strategyBreakdown,
      associations: associationsMade.map((a) => ({
        exam_topic: a.exam_topic,
        question_id: a.question_id,
        strategy: a.matching_strategy,
      })),
      remaining_unassigned: updatedTopicList.filter(
        (t) => t.question_id === null,
      ).length,
      structuredData: true,
    },
  );

  return updatedTopicList;
}
