import logger from '../../firebase/logger';
import prismaInstance, { DifficultyLevel } from '../../prisma';
import { quizGeneratorPromise } from '../../quizGenerator';

type QuizItem = {
  question: string;
  choices: string[];
  answerIndex: number;
  topic?: string;
  explanation: string;
  exam_id: string;
};

interface QuestionGenerationMessage {
  exam_id: string;
  cert_id: number;
  number_of_questions_to_generate: number;
}

export const handleExamQuestionsGeneration = async (
  messageData: QuestionGenerationMessage,
): Promise<void> => {
  const { exam_id, cert_id, number_of_questions_to_generate } = messageData;

  // Fetch certification name using cert_id
  const certification = await prismaInstance.certification.findUnique({
    where: { cert_id: cert_id },
    select: { name: true },
  });

  if (!certification) {
    throw new Error(`Certification with cert_id ${cert_id} not found`);
  }

  const certification_name = certification.name;

  logger.info(
    `Processing question generation for exam_id: ${exam_id}, cert: ${certification_name}, count: ${number_of_questions_to_generate}`,
  );

  try {
    // Update exam status to QUESTIONS_GENERATING
    await prismaInstance.examAttempt.update({
      where: { exam_id: exam_id },
      data: { exam_status: 'QUESTIONS_GENERATING' },
    });

    const quizGenerator = await quizGeneratorPromise;

    // The quizGenerator's max count is 50, so we might need to call it in batches
    const batchSize = 50;
    const batches = Math.ceil(number_of_questions_to_generate / batchSize);
    let allGeneratedItems: QuizItem[] = [];

    for (let i = 0; i < batches; i++) {
      const questionsInThisBatch = Math.min(
        batchSize,
        number_of_questions_to_generate - i * batchSize,
      );

      logger.info(
        `Generating batch ${
          i + 1
        }/${batches} with ${questionsInThisBatch} questions for exam ${exam_id}`,
      );

      const batchItems: QuizItem[] = await quizGenerator({
        subject: certification_name,
        count: questionsInThisBatch,
        exam_id: exam_id,
      });

      allGeneratedItems = [...allGeneratedItems, ...batchItems];
    }

    if (!allGeneratedItems || allGeneratedItems.length === 0) {
      logger.warn(
        `No questions generated by AI for exam_id: ${exam_id}. Updating exam status.`,
      );
      await prismaInstance.examAttempt.update({
        where: { exam_id: exam_id },
        data: { exam_status: 'QUESTION_GENERATION_FAILED' },
      });
      return;
    }

    logger.info(
      `Successfully generated ${allGeneratedItems.length} questions for exam ${exam_id}. Storing them...`,
    );

    // Get a default topic if available, or create one
    // let defaultTopic = await prismaInstance.topic.findFirst({
    //   where: {
    //     certTopics: {
    //       some: { cert_id: cert_id },
    //     },
    //   },
    // });

    // if (!defaultTopic) {
    //   // Create a default topic for this certification
    //   defaultTopic = await prismaInstance.topic.create({
    //     data: { name: `${certification_name} General` },
    //   });

    //   // Link it to the certification
    //   await prismaInstance.certTopic.create({
    //     data: {
    //       cert_id: cert_id,
    //       topic_id: defaultTopic.id,
    //     },
    //   });
    // }

    // Store questions and create exam user answers
    for (const item of allGeneratedItems) {
      // Ensure the item.exam_id matches for integrity
      if (item.exam_id !== exam_id) {
        logger.warn(
          `Mismatch in exam_id from generator. Expected ${exam_id}, got ${item.exam_id}. Skipping item.`,
        );
        continue;
      }

      // Find or create topic for this question
      // let questionTopic = defaultTopic;
      // if (item.topic) {
      //   const existingTopic = await prismaInstance.topic.findFirst({
      //     where: { name: item.topic },
      //   });

      //   if (existingTopic) {
      //     questionTopic = existingTopic;
      //   } else {
      //     // Create new topic if it doesn't exist
      //     questionTopic = await prismaInstance.topic.create({
      //       data: { name: item.topic },
      //     });

      //     // Link it to the certification
      //     await prismaInstance.certTopic.upsert({
      //       where: {
      //         cert_id_topic_id: {
      //           cert_id: cert_id,
      //           topic_id: questionTopic.id,
      //         },
      //       },
      //       create: {
      //         cert_id: cert_id,
      //         topic_id: questionTopic.id,
      //       },
      //       update: {}, // No update needed if already exists
      //     });
      //   }
      // }

      const newQuizQuestion = await prismaInstance.quizQuestion.create({
        data: {
          question_text: item.question,
          difficulty: DifficultyLevel.EASY,
          explanations: item.explanation,
          cert_id: cert_id,
          // topic_id: questionTopic.id,
          answerOptions: {
            create: item.choices.map((choice, index) => ({
              option_text: choice,
              is_correct: index === item.answerIndex,
            })),
          },
        },
      });

      // Create exam user answer entry linking this question to the exam
      await prismaInstance.examUserAnswer.create({
        data: {
          exam_id: exam_id,
          quiz_question_id: newQuizQuestion.quiz_question_id,
        },
      });
    }

    // Update exam status to READY after all questions are stored
    await prismaInstance.examAttempt.update({
      where: { exam_id: exam_id },
      data: {
        exam_status: 'READY',
      },
    });

    logger.info(
      `Successfully stored ${allGeneratedItems.length} questions and linked to exam ${exam_id}. Exam status: READY.`,
    );
  } catch (error) {
    logger.error(
      `Error processing question generation for exam_id ${exam_id}:`,
      error as any,
    );
    try {
      await prismaInstance.examAttempt.update({
        where: { exam_id: exam_id },
        data: { exam_status: 'QUESTION_GENERATION_FAILED' },
      });
    } catch (updateError) {
      logger.error(
        `Failed to update exam status to FAILED for exam ${exam_id} after error:`,
        updateError as any,
      );
    }
    throw error; // Re-throw to allow Pub/Sub to handle retries/dead-lettering
  }
};
