name: Deploy to Firebase Functions UAT on merge
on:
  push:
    branches:
      - uat
jobs:
  build_and_deploy_uat:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache npm Dependencies
        uses: actions/cache@v5
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm Dependencies
        run: npm ci
        working-directory: functions

      - name: Install Firebase CLI globally
        run: npm install -g firebase-tools

      - name: Create file - gcp_credentials.json
        run: |
          echo '${{ secrets.GCP_CREDENTIALS_JSON_UAT }}' | jq '.' > gcp_credentials.json
        working-directory: functions

      - name: Set Firebase Project to UAT
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./gcp_credentials.json"
          firebase use ${{ vars.GCP_PROJECT_ID_UAT }}
        working-directory: functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json

      - name: Enable required GCP APIs
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./gcp_credentials.json"
          gcloud auth activate-service-account --key-file=./gcp_credentials.json
          gcloud config set project ${{ vars.GCP_PROJECT_ID_UAT }}
          gcloud services enable cloudfunctions.googleapis.com
          gcloud services enable cloudbuild.googleapis.com
          gcloud services enable artifactregistry.googleapis.com
          gcloud services enable eventarc.googleapis.com
          gcloud services enable run.googleapis.com
          gcloud services enable logging.googleapis.com
          gcloud services enable firestore.googleapis.com
        working-directory: functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json

      - name: Create file - .env
        run: |
          echo "GCP_PROJECT_NUMBER=${{ vars.GCP_PROJECT_NUMBER_UAT }}" >> .env
          echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID_UAT }}" >> .env
          echo "GCP_REGION=${{ vars.GCP_REGION_UAT }}" >> .env
          echo "GCP_TASKS_HOST=${{ vars.GCP_TASKS_HOST_UAT }}" >> .env
          echo "GCP_TASKS_SERVICE_ACCOUNT=${{ vars.GCP_TASKS_SERVICE_ACCOUNT_UAT }}" >> .env

          echo "FRONTEND_URL=${{ vars.FRONTEND_URL_UAT }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL_UAT }}" >> .env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL_UAT }}" >> .env
          echo "PUBLIC_JWT_SECRET=${{ secrets.PUBLIC_JWT_SECRET_UAT }}" >> .env

          echo "UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL_UAT }}" >> .env
          echo "UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN_UAT }}" >> .env

          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY_UAT }}" >> .env
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET_UAT }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY_UAT }}" >> .env
        working-directory: functions

      - name: Set Firebase Project for Firestore Deployment
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./functions/gcp_credentials.json"
          firebase use ${{ vars.GCP_PROJECT_ID_UAT }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./functions/gcp_credentials.json

      - name: Deploy Firestore Rules and Indexes
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./functions/gcp_credentials.json"
          firebase deploy --only firestore:rules,firestore:indexes --non-interactive --debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./functions/gcp_credentials.json

      - name: Deploy Firebase Functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="./gcp_credentials.json"
          npm run deploy -- --force
        working-directory: functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ./gcp_credentials.json
