name: Deploy to Firebase Functions on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Cache npm Dependencies
        uses: actions/cache@v4
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm Dependencies
        run: npm ci
        working-directory: functions

      - name: Create file - gcp_credentials.json
        run: |
          echo '${{ secrets.GCP_CREDENTIALS_JSON }}' | jq '.' > gcp_credentials.json
        working-directory: functions

      - name: Create file - .env
        run: |
          echo "GCP_PROJECT_NUMBER=${{ vars.GCP_PROJECT_NUMBER }}" >> .env
          echo "GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}" >> .env
          echo "GCP_REGION=${{ vars.GCP_REGION }}" >> .env
          echo "GCP_TASKS_HOST=${{ vars.GCP_TASKS_HOST }}" >> .env
          echo "GCP_TASKS_SERVICE_ACCOUNT=${{ vars.GCP_TASKS_SERVICE_ACCOUNT }}" >> .env

          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "DIRECT_URL=${{ secrets.DIRECT_URL }}" >> .env
          echo "PUBLIC_JWT_SECRET=${{ secrets.PUBLIC_JWT_SECRET }}" >> .env

          echo "UPSTASH_REDIS_REST_URL=${{ secrets.UPSTASH_REDIS_REST_URL }}" >> .env
          echo "UPSTASH_REDIS_REST_TOKEN=${{ secrets.UPSTASH_REDIS_REST_TOKEN }}" >> .env
        working-directory: functions

      - name: Deploy Firebase Functions
        run: |
          npm run deploy
        working-directory: functions
