name: Deploy to Firebase Functions on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CO_WORKOUT_NEXT }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # - name: Cache Dependencies
      #   uses: actions/cache@v4
      #   id: cache-dependencies
      #   with:
      #     path: |
      #       ~/.npm
      #       ~/.cache/firebase
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Create GCP Credentials File
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CO_WORKOUT_NEXT }}' | jq '.' > gcp_credentials.json
        working-directory: functions

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CO_WORKOUT_NEXT }}

      - name: Build and Deploy
        run: |
          npm ci
          npm run deploy
        working-directory: functions
